version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  voterapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
  voteapi:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - redis
  pollapi:
    build: .
    ports:
      - "8080:8082"
    depends_on:
      - redis
